namespace TechnicianApi.Core.Entities;

public class DailySummary : BaseEntity
{
    public string TechnicianId { get; set; } = string.Empty;
    public DateTime Date { get; set; }

    // Task statistics
    public int TotalAssignments { get; set; }
    public int CompletedTasks { get; set; }
    public int PendingTasks { get; set; }
    public int DelayedTasks { get; set; }
    public int CancelledTasks { get; set; }

    // Performance metrics
    public decimal PerformanceScore { get; set; }
    public PerformanceAlertLevel AlertLevel { get; set; } = PerformanceAlertLevel.None;

    // Time tracking
    public int TotalWorkingMinutes { get; set; }
    public DateTime? FirstCheckIn { get; set; }
    public DateTime? LastCheckOut { get; set; }

    // Financial
    public int TotalRequisitions { get; set; }
    public decimal TotalRequisitionAmount { get; set; }

    // Auto-generated summary
    public string? AutoGeneratedNotes { get; set; }
    public virtual Attachment? Attachment { get; set; } = null!;
}

public enum PerformanceAlertLevel
{
    None,
    Amber,
    Red
}
