// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transaction.Infrastructure.Data;

#nullable disable

namespace Transaction.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20260121094245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transaction.Core.Entities.ReweighRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operator1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Operator2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeighbridgeTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("WeighbridgeTransactionId");

                    b.Property<decimal?>("Weight1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Weight1Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Weight2Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttemptNumber");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WeighbridgeTransactionId");

                    b.ToTable("ReweighRecords");
                });

            modelBuilder.Entity("Transaction.Core.Entities.WeighbridgeTransaction", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TicketID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketID"));

                    b.Property<int?>("ApiId")
                        .HasColumnType("integer")
                        .HasColumnName("api_id");

                    b.Property<DateTime?>("ChangeDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ChangeDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ChangeDesc")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ChangeDesc");

                    b.Property<int?>("CommodityID")
                        .HasColumnType("integer")
                        .HasColumnName("CommodityID");

                    b.Property<string>("CommodityName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CommodityName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CustomerName");

                    b.Property<int?>("DestinationID")
                        .HasColumnType("integer")
                        .HasColumnName("DestinationID");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DestinationName");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DriverName");

                    b.Property<string>("FirstWeight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("FirstWeight");

                    b.Property<DateTime>("FirstWeightDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FirstWeightDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NetWeight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NetWeight");

                    b.Property<string>("NoPlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("NoPlate");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Operation");

                    b.Property<int?>("OperatorID")
                        .HasColumnType("integer")
                        .HasColumnName("OperatorID");

                    b.Property<string>("OperatorID2nd")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("OperatorID2nd");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("OperatorName");

                    b.Property<string>("OperatorName2nd")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("OperatorName2nd");

                    b.Property<int?>("OriginID")
                        .HasColumnType("integer")
                        .HasColumnName("OriginID");

                    b.Property<string>("OriginName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("OriginName");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ReceiptNo");

                    b.Property<string>("ReweighPermission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ReweighPermission");

                    b.Property<string>("ScaleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ScaleName");

                    b.Property<string>("ScaleName2nd")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ScaleName2nd");

                    b.Property<string>("SecondWeight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SecondWeight");

                    b.Property<DateTime>("SecondWeightDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SecondWeightDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("Status");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("integer")
                        .HasColumnName("SupplierID");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SupplierName");

                    b.Property<int>("TransporterID")
                        .HasColumnType("integer")
                        .HasColumnName("TransporterID");

                    b.Property<string>("TransporterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TransporterName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("integer")
                        .HasColumnName("vehicleID");

                    b.Property<int?>("WeighBridgeID")
                        .HasColumnType("integer")
                        .HasColumnName("WeighBridgeID");

                    b.Property<string>("WeighBridgeName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("WeighBridgeName");

                    b.Property<string>("WeighBridgeName2nd")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("WeighBridgeName2nd");

                    b.Property<string>("WeighMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("WeighMode");

                    b.HasKey("TicketID");

                    b.HasIndex("FirstWeightDate");

                    b.HasIndex("NoPlate");

                    b.HasIndex("ReceiptNo");

                    b.HasIndex("Status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Transaction.Core.Entities.ReweighRecord", b =>
                {
                    b.HasOne("Transaction.Core.Entities.WeighbridgeTransaction", "WeighbridgeTransaction")
                        .WithMany()
                        .HasForeignKey("WeighbridgeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeighbridgeTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
