### YamlMime:ManagedReference
items:
- uid: UserService.Core.Configuration
  commentId: N:UserService.Core.Configuration
  id: UserService.Core.Configuration
  children:
  - UserService.Core.Configuration.JwtConfiguration
  langs:
  - csharp
  - vb
  name: UserService.Core.Configuration
  nameWithType: UserService.Core.Configuration
  fullName: UserService.Core.Configuration
  type: Namespace
  assemblies:
  - UserService.Core
references:
- uid: UserService.Core.Configuration.JwtConfiguration
  commentId: T:UserService.Core.Configuration.JwtConfiguration
  href: UserService.Core.Configuration.JwtConfiguration.html
  name: JwtConfiguration
  nameWithType: JwtConfiguration
  fullName: UserService.Core.Configuration.JwtConfiguration
