# Generated by Django 4.2.24 on 2025-09-24 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='License class name (e.g., Class A CDL, Class B CDL, Regular License)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this license allows')),
            ],
            options={
                'verbose_name': 'License Class',
                'verbose_name_plural': 'License Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tester_registration_enabled', models.BooleanField(default=True)),
                ('tester_login_enabled', models.BooleanField(default=True)),
                ('license_expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Number of days before license expiry to show warning')),
                ('require_profile_photo', models.BooleanField(default=True)),
                ('require_license_images', models.BooleanField(default=True)),
                ('require_id_images', models.BooleanField(default=True)),
                ('auto_approve_profile_updates', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
