# Generated by Django 4.2.24 on 2025-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_approve_user_types',
            field=models.JSONField(default=list, help_text="List of user types to auto-approve on registration (e.g., ['admin'])"),
        ),
    ]
