### YamlMime:ManagedReference
items:
- uid: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration
  commentId: T:QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration
  id: ModuleConfiguration
  parent: QaliTrack.MasterData.Api.Infrastructure
  children:
  - QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  langs:
  - csharp
  - vb
  name: ModuleConfiguration
  nameWithType: ModuleConfiguration
  fullName: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration
  type: Class
  source:
    remote:
      path: packages/QaliTrack.MasterData/src/QaliTrack.MasterData.Api/Infrastructure/ModuleConfiguration.cs
      branch: main
      repo: https://github.com/surgbc-projects/qalitrackservices.git
    id: ModuleConfiguration
    path: src/QaliTrack.MasterData.Api/Infrastructure/ModuleConfiguration.cs
    startLine: 8
  assemblies:
  - QaliTrack.MasterData.Api
  namespace: QaliTrack.MasterData.Api.Infrastructure
  syntax:
    content: public static class ModuleConfiguration
    content.vb: Public Module ModuleConfiguration
  inheritance:
  - System.Object
- uid: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  commentId: M:QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  id: ConfigureModules(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  isExtensionMethod: true
  parent: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration
  langs:
  - csharp
  - vb
  name: ConfigureModules(IServiceCollection)
  nameWithType: ModuleConfiguration.ConfigureModules(IServiceCollection)
  fullName: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  type: Method
  source:
    remote:
      path: packages/QaliTrack.MasterData/src/QaliTrack.MasterData.Api/Infrastructure/ModuleConfiguration.cs
      branch: main
      repo: https://github.com/surgbc-projects/qalitrackservices.git
    id: ConfigureModules
    path: src/QaliTrack.MasterData.Api/Infrastructure/ModuleConfiguration.cs
    startLine: 10
  assemblies:
  - QaliTrack.MasterData.Api
  namespace: QaliTrack.MasterData.Api.Infrastructure
  syntax:
    content: public static void ConfigureModules(this IServiceCollection services)
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: Public Shared Sub ConfigureModules(services As IServiceCollection)
  overload: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules*
references:
- uid: QaliTrack.MasterData.Api.Infrastructure
  commentId: N:QaliTrack.MasterData.Api.Infrastructure
  href: QaliTrack.html
  name: QaliTrack.MasterData.Api.Infrastructure
  nameWithType: QaliTrack.MasterData.Api.Infrastructure
  fullName: QaliTrack.MasterData.Api.Infrastructure
  spec.csharp:
  - uid: QaliTrack
    name: QaliTrack
    href: QaliTrack.html
  - name: .
  - uid: QaliTrack.MasterData
    name: MasterData
    href: QaliTrack.MasterData.html
  - name: .
  - uid: QaliTrack.MasterData.Api
    name: Api
    href: QaliTrack.MasterData.Api.html
  - name: .
  - uid: QaliTrack.MasterData.Api.Infrastructure
    name: Infrastructure
    href: QaliTrack.MasterData.Api.Infrastructure.html
  spec.vb:
  - uid: QaliTrack
    name: QaliTrack
    href: QaliTrack.html
  - name: .
  - uid: QaliTrack.MasterData
    name: MasterData
    href: QaliTrack.MasterData.html
  - name: .
  - uid: QaliTrack.MasterData.Api
    name: Api
    href: QaliTrack.MasterData.Api.html
  - name: .
  - uid: QaliTrack.MasterData.Api.Infrastructure
    name: Infrastructure
    href: QaliTrack.MasterData.Api.Infrastructure.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules*
  commentId: Overload:QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules
  href: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.html#QaliTrack_MasterData_Api_Infrastructure_ModuleConfiguration_ConfigureModules_Microsoft_Extensions_DependencyInjection_IServiceCollection_
  name: ConfigureModules
  nameWithType: ModuleConfiguration.ConfigureModules
  fullName: QaliTrack.MasterData.Api.Infrastructure.ModuleConfiguration.ConfigureModules
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  commentId: T:Microsoft.Extensions.DependencyInjection.IServiceCollection
  parent: Microsoft.Extensions.DependencyInjection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
- uid: Microsoft.Extensions.DependencyInjection
  commentId: N:Microsoft.Extensions.DependencyInjection
  isExternal: true
  name: Microsoft.Extensions.DependencyInjection
  nameWithType: Microsoft.Extensions.DependencyInjection
  fullName: Microsoft.Extensions.DependencyInjection
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
