### YamlMime:ManagedReference
items:
- uid: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration
  commentId: T:QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration
  id: DatabaseConfiguration
  parent: QaliTrack.MasterData.Api.Infrastructure
  children:
  - QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)
  langs:
  - csharp
  - vb
  name: DatabaseConfiguration
  nameWithType: DatabaseConfiguration
  fullName: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration
  type: Class
  source:
    remote:
      path: packages/QaliTrack.MasterData/src/QaliTrack.MasterData.Api/Infrastructure/DatabaseConfiguration.cs
      branch: main
      repo: https://github.com/surgbc-projects/qalitrackservices.git
    id: DatabaseConfiguration
    path: src/QaliTrack.MasterData.Api/Infrastructure/DatabaseConfiguration.cs
    startLine: 5
  assemblies:
  - QaliTrack.MasterData.Api
  namespace: QaliTrack.MasterData.Api.Infrastructure
  syntax:
    content: public static class DatabaseConfiguration
    content.vb: Public Module DatabaseConfiguration
  inheritance:
  - System.Object
- uid: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)
  commentId: M:QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)
  id: ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)
  isExtensionMethod: true
  parent: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration
  langs:
  - csharp
  - vb
  name: ConfigureDatabase(IServiceCollection, IConfiguration)
  nameWithType: DatabaseConfiguration.ConfigureDatabase(IServiceCollection, IConfiguration)
  fullName: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.Extensions.Configuration.IConfiguration)
  type: Method
  source:
    remote:
      path: packages/QaliTrack.MasterData/src/QaliTrack.MasterData.Api/Infrastructure/DatabaseConfiguration.cs
      branch: main
      repo: https://github.com/surgbc-projects/qalitrackservices.git
    id: ConfigureDatabase
    path: src/QaliTrack.MasterData.Api/Infrastructure/DatabaseConfiguration.cs
    startLine: 7
  assemblies:
  - QaliTrack.MasterData.Api
  namespace: QaliTrack.MasterData.Api.Infrastructure
  syntax:
    content: public static void ConfigureDatabase(this IServiceCollection services, IConfiguration configuration)
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    - id: configuration
      type: Microsoft.Extensions.Configuration.IConfiguration
    content.vb: Public Shared Sub ConfigureDatabase(services As IServiceCollection, configuration As IConfiguration)
  overload: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase*
references:
- uid: QaliTrack.MasterData.Api.Infrastructure
  commentId: N:QaliTrack.MasterData.Api.Infrastructure
  href: QaliTrack.html
  name: QaliTrack.MasterData.Api.Infrastructure
  nameWithType: QaliTrack.MasterData.Api.Infrastructure
  fullName: QaliTrack.MasterData.Api.Infrastructure
  spec.csharp:
  - uid: QaliTrack
    name: QaliTrack
    href: QaliTrack.html
  - name: .
  - uid: QaliTrack.MasterData
    name: MasterData
    href: QaliTrack.MasterData.html
  - name: .
  - uid: QaliTrack.MasterData.Api
    name: Api
    href: QaliTrack.MasterData.Api.html
  - name: .
  - uid: QaliTrack.MasterData.Api.Infrastructure
    name: Infrastructure
    href: QaliTrack.MasterData.Api.Infrastructure.html
  spec.vb:
  - uid: QaliTrack
    name: QaliTrack
    href: QaliTrack.html
  - name: .
  - uid: QaliTrack.MasterData
    name: MasterData
    href: QaliTrack.MasterData.html
  - name: .
  - uid: QaliTrack.MasterData.Api
    name: Api
    href: QaliTrack.MasterData.Api.html
  - name: .
  - uid: QaliTrack.MasterData.Api.Infrastructure
    name: Infrastructure
    href: QaliTrack.MasterData.Api.Infrastructure.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase*
  commentId: Overload:QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase
  href: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.html#QaliTrack_MasterData_Api_Infrastructure_DatabaseConfiguration_ConfigureDatabase_Microsoft_Extensions_DependencyInjection_IServiceCollection_Microsoft_Extensions_Configuration_IConfiguration_
  name: ConfigureDatabase
  nameWithType: DatabaseConfiguration.ConfigureDatabase
  fullName: QaliTrack.MasterData.Api.Infrastructure.DatabaseConfiguration.ConfigureDatabase
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  commentId: T:Microsoft.Extensions.DependencyInjection.IServiceCollection
  parent: Microsoft.Extensions.DependencyInjection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.DependencyInjection
  commentId: N:Microsoft.Extensions.DependencyInjection
  isExternal: true
  name: Microsoft.Extensions.DependencyInjection
  nameWithType: Microsoft.Extensions.DependencyInjection
  fullName: Microsoft.Extensions.DependencyInjection
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
