// <auto-generated />
using System;
using ComplianceService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplianceService.Infrastructure.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20250702223023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComplianceViolationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ComplianceViolationId");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ComplianceAudits");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CheckedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ComplianceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("ComplianceRuleId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Result");

                    b.HasIndex("Status");

                    b.ToTable("ComplianceChecks");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PenaltyCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("KES");

                    b.Property<int?>("RegulatoryStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MEDIUM");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("RegulatoryStandardId");

                    b.HasIndex("RuleType");

                    b.ToTable("ComplianceRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "GROSS_WEIGHT",
                            ConfigurationJson = "{\"maxWeight\": 56000, \"unit\": \"KG\", \"penaltyRate\": 5.0}",
                            CreatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 85, DateTimeKind.Utc).AddTicks(3689),
                            CreatedBy = "SYSTEM",
                            Description = "Check if vehicle gross weight exceeds legal limits",
                            IsActive = true,
                            MaxValue = 56000m,
                            Name = "Gross Weight Compliance",
                            PenaltyAmount = 5.0m,
                            PenaltyCurrency = "KES",
                            RuleType = "WEIGHT",
                            Severity = "HIGH",
                            Unit = "KG",
                            UpdatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 85, DateTimeKind.Utc).AddTicks(8020),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Category = "EXPIRY",
                            ConfigurationJson = "{\"warningDays\": 30, \"criticalDays\": 7}",
                            CreatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 86, DateTimeKind.Utc).AddTicks(131),
                            CreatedBy = "SYSTEM",
                            Description = "Monitor driver license expiry dates",
                            IsActive = true,
                            MinValue = 0m,
                            Name = "License Expiry Check",
                            PenaltyCurrency = "KES",
                            RuleType = "LICENSE",
                            Severity = "CRITICAL",
                            Unit = "DAYS",
                            UpdatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 86, DateTimeKind.Utc).AddTicks(132),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ComplianceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExcessValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LicenseMonitoringId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LimitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PenaltyCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("KES");

                    b.Property<string>("ResolutionNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RouteRestrictionsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MEDIUM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeighbridgeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WeightLimitsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceRuleId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicenseMonitoringId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RouteRestrictionsId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ViolationType");

                    b.HasIndex("WeightLimitsId");

                    b.ToTable("ComplianceViolations");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.LicenseMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiryWarningDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextCheckDue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ACTIVE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("LicenseNumber");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.ToTable("LicenseMonitoring");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.RegulatoryStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("KENYA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryBody")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("1.0");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("IsActive");

                    b.HasIndex("StandardType");

                    b.ToTable("RegulatoryStandards");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.RouteRestrictions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeekdaysOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeekendsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenaltyCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("KES");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("RestrictedFromTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("RestrictedToTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestrictionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MEDIUM");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ViolationPenalty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RestrictionType");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteRestrictions");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.WeightLimits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAxleCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAxleWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxFrontAxleWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxGrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxRearAxleWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverweightPenaltyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PenaltyCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("KES");

                    b.Property<string>("RegulatoryReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeighbridgeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("VehicleClass");

                    b.HasIndex("VehicleType");

                    b.ToTable("WeightLimits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 82, DateTimeKind.Utc).AddTicks(8332),
                            CreatedBy = "SYSTEM",
                            Description = "Standard weight limits for trucks in Kenya",
                            EffectiveDate = new DateTime(2025, 7, 2, 22, 30, 22, 82, DateTimeKind.Utc).AddTicks(1187),
                            IsActive = true,
                            MaxAxleCount = 5,
                            MaxAxleWeight = 18000m,
                            MaxFrontAxleWeight = 7000m,
                            MaxGrossWeight = 56000m,
                            MaxRearAxleWeight = 18000m,
                            Name = "Standard Truck Weight Limits",
                            OrganizationId = "",
                            OverweightPenaltyRate = 5.0m,
                            PenaltyCurrency = "KES",
                            RegulatoryReference = "Traffic Act Cap 403",
                            RouteId = "",
                            UpdatedAt = new DateTime(2025, 7, 2, 22, 30, 22, 82, DateTimeKind.Utc).AddTicks(8820),
                            UpdatedBy = "SYSTEM",
                            VehicleClass = "STANDARD",
                            VehicleType = "TRUCK",
                            WeighbridgeId = ""
                        });
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceAudit", b =>
                {
                    b.HasOne("ComplianceService.Core.Entities.ComplianceViolation", "ComplianceViolation")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ComplianceViolationId");

                    b.Navigation("ComplianceViolation");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceCheck", b =>
                {
                    b.HasOne("ComplianceService.Core.Entities.ComplianceRule", "ComplianceRule")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("ComplianceRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComplianceRule");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceRule", b =>
                {
                    b.HasOne("ComplianceService.Core.Entities.RegulatoryStandard", null)
                        .WithMany("ComplianceRules")
                        .HasForeignKey("RegulatoryStandardId");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceViolation", b =>
                {
                    b.HasOne("ComplianceService.Core.Entities.ComplianceRule", "ComplianceRule")
                        .WithMany("Violations")
                        .HasForeignKey("ComplianceRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceService.Core.Entities.LicenseMonitoring", null)
                        .WithMany("Violations")
                        .HasForeignKey("LicenseMonitoringId");

                    b.HasOne("ComplianceService.Core.Entities.RouteRestrictions", null)
                        .WithMany("Violations")
                        .HasForeignKey("RouteRestrictionsId");

                    b.HasOne("ComplianceService.Core.Entities.WeightLimits", null)
                        .WithMany("Violations")
                        .HasForeignKey("WeightLimitsId");

                    b.Navigation("ComplianceRule");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceRule", b =>
                {
                    b.Navigation("ComplianceChecks");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.ComplianceViolation", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.LicenseMonitoring", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.RegulatoryStandard", b =>
                {
                    b.Navigation("ComplianceRules");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.RouteRestrictions", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ComplianceService.Core.Entities.WeightLimits", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
