# Generated by Django 4.2.24 on 2025-09-24 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('trip_create', 'Trip Created'), ('trip_start', 'Trip Started'), ('trip_complete', 'Trip Completed'), ('expense_add', 'Expense Added'), ('receipt_upload', 'Receipt Uploaded'), ('profile_update', 'Profile Updated'), ('mileage_record', 'Mileage Recorded'), ('location_update', 'Location Updated'), ('app_open', 'App Opened'), ('document_upload', 'Document Uploaded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(help_text='National ID or equivalent', max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='driver_profiles/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('license_front_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('license_back_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_versions', to='drivers.driver')),
                ('license_classes', models.ManyToManyField(blank=True, help_text="Driver's license classes", to='settings.licenseclass')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfileChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='drivers.driverprofile')),
                ('old_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='drivers.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
