# Generated by Django 4.2.24 on 2025-09-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_driver_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveractivity',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['driver', 'is_current'], name='drivers_dri_driver__ca47e1_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['status'], name='drivers_dri_status_1fdaae_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['license_expiry_date'], name='drivers_dri_license_a8ff36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverprofile',
            unique_together={('driver', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='driveractivity',
            index=models.Index(fields=['driver', 'created_at'], name='drivers_dri_driver__55e4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='driveractivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='drivers_dri_activit_16b3fd_idx'),
        ),
    ]
