# Generated by Django 4.2.24 on 2026-02-11 10:40

import django.core.validators
from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, storage=storage.DriverProfileStorage, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, storage=storage.DriverProfileStorage, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_back_image',
            field=models.ImageField(blank=True, null=True, storage=storage.DriverProfileStorage, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_front_image',
            field=models.ImageField(blank=True, null=True, storage=storage.DriverProfileStorage, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=storage.DriverProfileStorage, upload_to='driver_profiles/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
