namespace TechnicianApi.Core.DTOs.DailySummary;

public class DailySummaryResponseDto
{
    public string Id { get; set; } = string.Empty;
    public string TechnicianId { get; set; } = string.Empty;
    public DateTime Date { get; set; }
    public int TotalAssignments { get; set; }
    public int CompletedTasks { get; set; }
    public int PendingTasks { get; set; }
    public int DelayedTasks { get; set; }
    public int CancelledTasks { get; set; }
    public decimal PerformanceScore { get; set; }
    public string AlertLevel { get; set; } = string.Empty;
    public int TotalWorkingMinutes { get; set; }
    public DateTime? FirstCheckIn { get; set; }
    public DateTime? LastCheckOut { get; set; }
    public int TotalRequisitions { get; set; }
    public decimal TotalRequisitionAmount { get; set; }
    public string? AutoGeneratedNotes { get; set; }
    public DateTime CreatedAt { get; set; }
}
