{{- if and .Values.userService.enabled .Values.userService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "technician-service.fullname" . }}-user-service
  labels:
    {{- include "technician-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "technician-service.fullname" . }}-user-service
  minReplicas: {{ .Values.userService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.userService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.userService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.userService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
