using Microsoft.AspNetCore.Http;

namespace Transaction.Core.DTOs;

public class TransactionReadDto
{
    public string TicketID { get; set; } = string.Empty;
    public string ReceiptNo { get; set; } = string.Empty;
    
    // Weight Information
    public string FirstWeight { get; set; } = string.Empty;
    public string? SecondWeight { get; set; }
    public string? NetWeight { get; set; }
    
    // Vehicle Information
    public string? VehicleID { get; set; }
    public string NoPlate { get; set; } = string.Empty;
    public string DriverName { get; set; } = string.Empty;
    
    // Commodity Information
    public string? CommodityID { get; set; }
    public string? CommodityName { get; set; }
    
    // Supplier Information
    public string? SupplierID { get; set; }
    public string? SupplierName { get; set; }
    
    // Customer Information
    public string? CustomerID { get; set; }
    public string? CustomerName { get; set; }
    
    // Transporter Information
    public string TransporterID { get; set; } = string.Empty;
    public string TransporterName { get; set; } = string.Empty;
    
    // Origin and Destination
    public string? OriginID { get; set; }
    public string? OriginName { get; set; }
    public string? DestinationID { get; set; }
    public string? DestinationName { get; set; }
    
    // Weighbridge Information - First Weighing
    public string? WeighBridgeID { get; set; }
    public string? WeighBridgeName { get; set; }
    public string? ScaleName { get; set; }
    public string? OperatorID { get; set; }
    public string? OperatorName { get; set; }
    
    // Weighbridge Information - Second Weighing
    public string? WeighBridgeName2nd { get; set; }
    public string? ScaleName2nd { get; set; }
    public string? OperatorID2nd { get; set; }
    public string? OperatorName2nd { get; set; }
    
    // Operational Details
    public string? WeighMode { get; set; }
    public string? Operation { get; set; }
    
    // Date Information
    public DateTime FirstWeightDate { get; set; }
    public DateTime SecondWeightDate { get; set; }
    
    // Transaction Status and Modifications
    public string Status { get; set; } = "Active";
    public string? ReweighPermission { get; set; }
    public string? ChangeDesc { get; set; }
    public DateTime? ChangeDate { get; set; }
    
    // API Integration
    public string? ApiId { get; set; }
    
    // Base properties
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// DTO for creating a new transaction.
/// NOTE: ReceiptNo is NOT included here as it is auto-generated by the system.
/// The receipt number will be in the format: QSL-YYYYMMDD-XXXXXX
/// </summary>
public class CreateTransactionDto
{
    // Vehicle Information (Required)
    public string NoPlate { get; set; } = string.Empty;
    public string DriverName { get; set; } = string.Empty;
    public string? VehicleID { get; set; }
    
    // Weight Information (First weight is required)
    public string FirstWeight { get; set; } = string.Empty;
    
    // Transporter Information (Required)
    public string TransporterID { get; set; } = string.Empty;
    public string TransporterName { get; set; } = string.Empty;
    
    // Weighing Information (Optional)
    public string? WeighBridgeID { get; set; }
    public string? WeighBridgeName { get; set; }
    public string? ScaleName { get; set; }
    public string? OperatorID { get; set; }
    public string? OperatorName { get; set; }
    
    // Commodity Information (Optional)
    public string? CommodityID { get; set; }
    public string? CommodityName { get; set; }
    
    // Supplier Information (Optional)
    public string? SupplierID { get; set; }
    public string? SupplierName { get; set; }
    
    // Customer Information (Optional)
    public string? CustomerID { get; set; }
    public string? CustomerName { get; set; }
    
    // Origin and Destination (Optional)
    public string? OriginID { get; set; }
    public string? OriginName { get; set; }
    public string? DestinationID { get; set; }
    public string? DestinationName { get; set; }
    
    // Operational Details (Optional)
    public string? WeighMode { get; set; }
    public string? Operation { get; set; }
    
    public string? Notes { get; set; }
    
    // NOTE: ReceiptNo is auto-generated and should NOT be provided by the client
    // NOTE: TicketID is auto-generated as a GUID and should NOT be provided by the client
}

/// <summary>
/// DTO for updating an existing transaction.
/// NOTE: ReceiptNo cannot be updated as it's a permanent identifier.
/// </summary>
public class UpdateTransactionDto
{
    // Vehicle Information
    public string? NoPlate { get; set; }
    public string? DriverName { get; set; }
    public string? VehicleID { get; set; }
    
    // Weight Information
    public string? SecondWeight { get; set; }
    
    // Commodity Information
    public string? CommodityID { get; set; }
    public string? CommodityName { get; set; }
    
    // Supplier Information
    public string? SupplierID { get; set; }
    public string? SupplierName { get; set; }
    
    // Customer Information
    public string? CustomerID { get; set; }
    public string? CustomerName { get; set; }
    
    // Transporter Information
    public string? TransporterID { get; set; }
    public string? TransporterName { get; set; }
    
    // Origin and Destination
    public string? OriginID { get; set; }
    public string? OriginName { get; set; }
    public string? DestinationID { get; set; }
    public string? DestinationName { get; set; }
    
    // Weighbridge Information - Second Weighing
    public string? WeighBridgeName2nd { get; set; }
    public string? ScaleName2nd { get; set; }
    public string? OperatorID2nd { get; set; }
    public string? OperatorName2nd { get; set; }
    
    // Operational Details
    public string? WeighMode { get; set; }
    public string? Operation { get; set; }
    
    public string? ChangeDesc { get; set; }
    
    // NOTE: ReceiptNo cannot be changed after creation
}

public class AddSecondWeightDto
{
    public string TicketID { get; set; } = string.Empty;
    public string SecondWeight { get; set; } = string.Empty;
    public string? WeighBridgeName2nd { get; set; }
    public string? ScaleName2nd { get; set; }
    public string? OperatorID2nd { get; set; }
    public string? OperatorName2nd { get; set; }
    public string? Notes { get; set; }
}

public class CompleteTransactionDto
{
    public string TicketID { get; set; } = string.Empty;
}

public class RequestReweighDto
{
    public string TicketID { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
}