apiRules:
- exclude:
    uidRegex: .*\.Tests.*
    type: Namespace
- exclude:
    uidRegex: .*\.Tests.*
    type: Type
- include:
    uidRegex: ^QaliTrack\.Gateway\..*
    type: Namespace
- include:
    uidRegex: ^QaliTrack\.Gateway\..*
    type: Type