apiVersion: v2
name: backup-service
description: Qalitrack Backup Service - Automated database backup and recovery
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - qalitrack
  - backup
  - recovery
  - database

maintainers:
  - name: Qalitrack Team
    email: dev@qalitrack.com

home: https://github.com/Qalitrack/qalitrackservices
sources:
  - https://github.com/Qalitrack/qalitrackservices
