# Generated by Django 4.2.24 on 2025-09-24 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMileage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_mileage', models.FloatField()),
                ('end_mileage', models.FloatField()),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='mileage_images/')),
                ('proof_end_image', models.ImageField(blank=True, null=True, upload_to='mileage_images/')),
                ('date', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to='drivers.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to='fleet.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_location_coords', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates of start location', null=True, srid=4326)),
                ('end_location_coords', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates of end location', null=True, srid=4326)),
                ('start_mileage', models.FloatField(blank=True, null=True)),
                ('end_mileage', models.FloatField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('proof_end_image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('total_mileage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='receipts/')),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_details', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='trips.expense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip'),
        ),
    ]
