# Generated by Django 4.2.24 on 2025-09-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_material_location_alter_material_name_and_more'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Type of material transported', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.material'),
        ),
        migrations.AddField(
            model_name='trip',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost to purchase the material for this trip', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='material_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant of the material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.materialvariant'),
        ),
    ]
