# Generated by Django 4.2.24 on 2025-09-25 05:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_material_trip_material_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current GPS coordinates when trip starts', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='trip',
            name='material_loading_photos',
            field=models.JSONField(blank=True, default=list, help_text='URLs to material loading confirmation photos'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
