# Generated by Django 4.2.24 on 2025-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_current_location_coords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, help_text='Optional receipt photo', null=True, upload_to='expense_receipts/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in KSh', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_mileage',
            field=models.FloatField(blank=True, help_text='Set when trip is completed', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='proof_end_image',
            field=models.ImageField(blank=True, help_text='End mileage photo - uploaded when ending trip', null=True, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Start mileage photo - uploaded when starting trip', null=True, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_mileage',
            field=models.FloatField(blank=True, help_text='Set when trip is started, not during creation', null=True),
        ),
    ]
