# Generated by Django 4.2.24 on 2025-11-11 20:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_expense_receipt_photo_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='custom_trip_type',
            field=models.CharField(blank=True, help_text="Custom trip type if predefined types don't apply", max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current GPS coordinates of the truck when trip is created', null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the trip type', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this trip type entails')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this trip type is available for selection')),
                ('category', models.CharField(choices=[('loaded', 'Loaded Trip'), ('empty', 'Empty Trip'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', help_text='Category of the trip type', max_length=50)),
                ('empty_trip_option', models.CharField(blank=True, help_text='For empty trips: e.g., carwash, starting day, ending day', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this trip type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trip_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Type',
                'verbose_name_plural': 'Trip Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.ForeignKey(blank=True, help_text='Type of trip - can be predefined or custom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.triptype'),
        ),
    ]
