# Generated by Django 4.2.24 on 2025-11-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_materialphoto_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0005_trip_custom_trip_type_trip_truck_location_coords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptype',
            name='material_requirement',
            field=models.CharField(choices=[('none', 'No Materials'), ('optional', 'Optional Materials'), ('mandatory', 'Mandatory Materials')], default='none', help_text='Whether this trip type requires materials', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, help_text='Optional receipt photo', null=True, storage=storage.ExpenseReceiptStorage, upload_to='expense_receipts/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(storage=storage.ReceiptStorage, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='proof_end_image',
            field=models.ImageField(blank=True, help_text='End mileage photo - uploaded when ending trip', null=True, storage=storage.TripImageStorage, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Start mileage photo - uploaded when starting trip', null=True, storage=storage.TripImageStorage, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='vehiclemileage',
            name='proof_end_image',
            field=models.ImageField(blank=True, null=True, storage=storage.TripImageStorage, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='vehiclemileage',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, storage=storage.TripImageStorage, upload_to='trip_images/'),
        ),
        migrations.CreateModel(
            name='TripMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity of material (if applicable)', max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this material in this trip', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for this material (quantity * unit_cost)', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this material was added to the trip')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this material for the trip')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this material to the trip', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_materials', to='fleet.material')),
                ('material_variant', models.ForeignKey(blank=True, help_text='Specific variant of the material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_materials', to='fleet.materialvariant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_materials', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Material',
                'verbose_name_plural': 'Trip Materials',
                'ordering': ['added_at'],
                'unique_together': {('trip', 'material', 'material_variant')},
            },
        ),
    ]
