apiVersion: v2
name: transaction-service
description: Qalitrack Transaction Service - Weighbridge transaction processing and management
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - qalitrack
  - transactions
  - weighbridge
  - weighing

maintainers:
  - name: Qalitrack Team
    email: dev@qalitrack.com

home: https://github.com/Qalitrack/qalitrackservices
sources:
  - https://github.com/Qalitrack/qalitrackservices
