### YamlMime:ManagedReference
items:
- uid: QaliTrackGateway.Configuration
  commentId: N:QaliTrackGateway.Configuration
  id: QaliTrackGateway.Configuration
  children:
  - QaliTrackGateway.Configuration.AuditSettings
  - QaliTrackGateway.Configuration.MonitoringSettings
  - QaliTrackGateway.Configuration.ServiceRegistrationDefaults
  langs:
  - csharp
  - vb
  name: QaliTrackGateway.Configuration
  nameWithType: QaliTrackGateway.Configuration
  fullName: QaliTrackGateway.Configuration
  type: Namespace
  assemblies:
  - QaliTrack.Gateway
references:
- uid: QaliTrackGateway.Configuration.AuditSettings
  commentId: T:QaliTrackGateway.Configuration.AuditSettings
  href: QaliTrackGateway.Configuration.AuditSettings.html
  name: AuditSettings
  nameWithType: AuditSettings
  fullName: QaliTrackGateway.Configuration.AuditSettings
- uid: QaliTrackGateway.Configuration.MonitoringSettings
  commentId: T:QaliTrackGateway.Configuration.MonitoringSettings
  href: QaliTrackGateway.Configuration.MonitoringSettings.html
  name: MonitoringSettings
  nameWithType: MonitoringSettings
  fullName: QaliTrackGateway.Configuration.MonitoringSettings
- uid: QaliTrackGateway.Configuration.ServiceRegistrationDefaults
  commentId: T:QaliTrackGateway.Configuration.ServiceRegistrationDefaults
  parent: QaliTrackGateway.Configuration
  href: QaliTrackGateway.Configuration.ServiceRegistrationDefaults.html
  name: ServiceRegistrationDefaults
  nameWithType: ServiceRegistrationDefaults
  fullName: QaliTrackGateway.Configuration.ServiceRegistrationDefaults
- uid: QaliTrackGateway.Configuration
  commentId: N:QaliTrackGateway.Configuration
  href: QaliTrackGateway.html
  name: QaliTrackGateway.Configuration
  nameWithType: QaliTrackGateway.Configuration
  fullName: QaliTrackGateway.Configuration
  spec.csharp:
  - uid: QaliTrackGateway
    name: QaliTrackGateway
    href: QaliTrackGateway.html
  - name: .
  - uid: QaliTrackGateway.Configuration
    name: Configuration
    href: QaliTrackGateway.Configuration.html
  spec.vb:
  - uid: QaliTrackGateway
    name: QaliTrackGateway
    href: QaliTrackGateway.html
  - name: .
  - uid: QaliTrackGateway.Configuration
    name: Configuration
    href: QaliTrackGateway.Configuration.html
