apiVersion: v2
name: technician-service
description: Qalitrack Technician Service - Technician management and operations
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - qalitrack
  - technician
  - management
  - operations

maintainers:
  - name: Qalitrack Team
    email: dev@qalitrack.com

home: https://github.com/Qalitrack/qalitrackservices
sources:
  - https://github.com/Qalitrack/qalitrackservices
