# Generated by Django 4.2.24 on 2025-09-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='destination',
        ),
        migrations.AlterField(
            model_name='material',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.trip'),
        ),
    ]
