# Generated by Django 4.2.24 on 2025-09-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_driver_from_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='photo',
        ),
    ]
