# Generated by Django 4.2.24 on 2025-09-18 21:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_material_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='trip',
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic location where this material was recorded', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='material',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='material_photos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='material_photos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='material_photos/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates of end location', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates of start location', null=True, srid=4326),
        ),
    ]
