# Generated by Django 4.2.24 on 2025-09-18 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_material_quantity_remove_material_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='material',
            name='photo3',
        ),
        migrations.CreateModel(
            name='MaterialPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='material_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
