# Generated by Django 4.2.24 on 2025-09-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_material_photo1_remove_material_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='base_email',
        ),
    ]
