# Generated by Django 4.2.24 on 2025-09-19 08:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customuser_base_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(help_text='National ID or equivalent', max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('license_class', models.CharField(default='C', help_text='License class (A, B, C, etc.)', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='driver_profiles/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('license_front_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('license_back_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_versions', to='core.driver')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_driver_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_approve_profile_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_expiry_warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days before license expiry to show warning'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_id_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_license_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_profile_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DriverProfileChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed')], max_length=20)),
                ('new_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='core.driverprofile')),
                ('old_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='core.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('trip_create', 'Trip Created'), ('trip_start', 'Trip Started'), ('trip_complete', 'Trip Completed'), ('expense_add', 'Expense Added'), ('receipt_upload', 'Receipt Uploaded'), ('profile_update', 'Profile Updated'), ('mileage_record', 'Mileage Recorded'), ('location_update', 'Location Updated'), ('app_open', 'App Opened'), ('document_upload', 'Document Uploaded')], max_length=20)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['driver', 'is_current'], name='core_driver_driver__e00bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['status'], name='core_driver_status_79afa2_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['license_expiry_date'], name='core_driver_license_fca9a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverprofile',
            unique_together={('driver', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='driveractivity',
            index=models.Index(fields=['driver', 'created_at'], name='core_driver_driver__e6f0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='driveractivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='core_driver_activit_426a84_idx'),
        ),
    ]
