# Generated by Django 4.2.24 on 2025-09-23 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_driverprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='License class code (e.g., A, B, C)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., Class A, CDL)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this license allows')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'License Class',
                'verbose_name_plural': 'License Classes',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='driveractivity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='driverprofilechange',
            name='updated_at',
        ),
    ]
