# Generated by Django 4.2.24 on 2025-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_licenseclass_remove_driveractivity_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseclass',
            options={'ordering': ['name'], 'verbose_name': 'License Class', 'verbose_name_plural': 'License Classes'},
        ),
        migrations.RemoveField(
            model_name='licenseclass',
            name='code',
        ),
        migrations.RemoveField(
            model_name='licenseclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='licenseclass',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='licenseclass',
            name='name',
            field=models.CharField(help_text='License class name (e.g., Class A CDL, Class B CDL, Regular License)', max_length=100, unique=True),
        ),
    ]
