# Generated by Django 4.2.24 on 2025-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_simplify_license_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_class',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_classes',
            field=models.ManyToManyField(blank=True, help_text="Driver's license classes", to='core.licenseclass'),
        ),
    ]
