services:
  mongodb:
    image: mongo:7
    container_name: qs-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: products_dashboard_db
    volumes:
      - mongodb_data_prod:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - website_prod_qs_network

  backend:
    image: ghcr.io/qalitrack/qalitrackservices/qs-website-backend:main
    container_name: qs-backend-prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - website_prod_qs_network

  frontend:
    image: ghcr.io/qalitrack/qalitrackservices/qs-website-frontend:main
    container_name: qs-frontend-prod
    restart: unless-stopped
    #ports:
    #  - "3001:80"
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=https://qalibrated.co.ke/api
      - VITE_ALLOWED_HOSTS=localhost,qalibrated.co.ke
    depends_on:
      - backend
    networks:
      - website_prod_qs_network

volumes:
  mongodb_data_prod:

networks:
  website_prod_qs_network:
    driver: bridge
    name: website_prod_qs_network
