# Generated by Django 4.2.24 on 2025-09-24 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='location',
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Base material name (e.g., Sand, Stone, Cement)', max_length=255),
        ),
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Variant name (e.g., Darugo, Kajido, River Sand)', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='fleet.material')),
            ],
            options={
                'unique_together': {('material', 'name')},
            },
        ),
    ]
