# Generated by Django 4.2.24 on 2025-09-24 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_material_location_alter_material_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVariantPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='material_variant_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('material_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.materialvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
