# Generated by Django 4.2.24 on 2025-11-11 20:28

from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_materialvariantphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialphoto',
            name='photo',
            field=models.ImageField(storage=storage.MaterialPhotoStorage, upload_to='material_photos/'),
        ),
        migrations.AlterField(
            model_name='materialvariantphoto',
            name='photo',
            field=models.ImageField(storage=storage.MaterialPhotoStorage, upload_to='material_variant_photos/'),
        ),
    ]
